[build]
  publish = "build"
  command = "npm run build"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Performance
    X-DNS-Prefetch-Control = "on"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images with long expiry
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000" # 30 days

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=2592000" # 30 days

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000" # 30 days

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=2592000" # 30 days

# Cache CSS and JS
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=2592000" # 30 days

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=2592000" # 30 days

# Cache fonts
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" # 1 year

# Redirects (same as _redirects file, but in TOML format)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable compression (Netlify does this automatically, but explicit is better)
[build.environment]
  NODE_VERSION = "18"

# Optimize images automatically (if you have Netlify Pro)
# [plugins]
#   [[plugins.package]]
#     package = "@netlify/plugin-nextjs"
